version: '3.7'
services:
  app:
    image: nahumt/respirar:latest
    env_file:
      - ./env/respirar.base.env
    depends_on:
      - database
      - cache
  database:
    image: postgres:12.0-alpine
  cache:
    image: redis:latest
volumes:
  postgres_data:
