version: '3.7'
services:
  app:
    image: nahumt/respirar:dev
    build:
      context: .
      target: dev
    command: python manage.py runserver 0:8000
    depends_on:
      - db
      - cache
    env_file:
      - ./env/app/.dev.env
    ports:
      - 8000:8000
    volumes:
      - .:/projects/respirar/
    networks:
      - backend
      - frontend
  db:
    env_file:
      - ./env/db/.dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      backend:
        aliases:
          - database
  cache:
    ports:
      - 6379:6379
volumes:
  postgres_data:
networks:
  frontend:
    name: respirar_frontend
    driver: bridge
  backend:
    name: respirar_backend
    driver: bridge