version: '3.7'
services:
  app:
    image: nahumt/respirar:latest
    build:
      context: .
      target: prod
    command: uwsgi --ini uwsgi/uwsgi_app_prod.ini
    depends_on:
      - db
      - cache
    env_file:
      - ./env/app/.prod.env
    ports:
      - 8000
    networks:
      - backend
      - frontend
    volumes:
      - static_volume:/home/app/respirar/staticfiles
      - media_volume:/home/app/respirar/mediafiles
  db:
    env_file:
      - ./env/db/.prod.env
    networks:
      backend:
        aliases:
          - database
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
  cache:
    ports:
      - 6379:6379
    networks:
      - backend
  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
      - 8081:80
    networks:
      backend:
        aliases:
          - nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/app/respirar/staticfiles
      - media_volume:/home/app/respirar/mediafiles
volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
networks:
  frontend:
    name: respirar_frontend
    driver: bridge
  backend:
    name: respirar_backend
    driver: bridge
